//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraWAF.WebPages.Bll.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeraWAF.WebPages.Bll.Resources.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted user.
        /// </summary>
        public static string DeletedUser {
            get {
                return ResourceManager.GetString("DeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to female.
        /// </summary>
        public static string FemaleGender {
            get {
                return ResourceManager.GetString("FemaleGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img data-href=&quot;{0}&quot; src=&quot;/Images/blank.gif&quot; width=&quot;{1}&quot; height=&quot;{2}&quot; class=&quot;jail {3} hide&quot; alt=&quot;{4}&quot; /&gt;&lt;noscript&gt;&lt;img property=&quot;sc:image&quot; src=&quot;{0}&quot; width=&quot;{1}&quot; height=&quot;{2}&quot; class=&quot;{3}&quot; alt=&quot;{4}&quot; /&gt;&lt;/noscript&gt;.
        /// </summary>
        public static string JailImageMarkup {
            get {
                return ResourceManager.GetString("JailImageMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img data-href=&quot;{0}&quot; src=&quot;/Images/blank.gif&quot; alt=&quot;{1}&quot; class=&quot;jail hide&quot; /&gt;&lt;noscript&gt;&lt;img  property=&quot;sc:image&quot; src=&quot;{0}&quot; alt=&quot;{1}&quot; /&gt;&lt;/noscript&gt;.
        /// </summary>
        public static string JailImageMarkup2 {
            get {
                return ResourceManager.GetString("JailImageMarkup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img data-href=&quot;{0}&quot; src=&quot;/Images/blank.gif&quot; class=&quot;jail hide&quot; alt=&quot;Unspecified&quot; /&gt;&lt;noscript&gt;&lt;img property=&quot;sc:image&quot; src=&quot;{0}&quot; alt=&quot;Unspecified&quot; /&gt;&lt;/noscript&gt;.
        /// </summary>
        public static string JailImageMarkup3 {
            get {
                return ResourceManager.GetString("JailImageMarkup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img data-href=&quot;{0}&quot; src=&quot;/Images/blank.gif&quot; alt=&quot;{1}&quot; class=&quot;jail {2} hide&quot; /&gt;&lt;noscript&gt;&lt;img property=&quot;sc:image&quot; src=&quot;{0}&quot; alt=&quot;{1}&quot; class=&quot;{2}&quot; /&gt;&lt;/noscript&gt;.
        /// </summary>
        public static string JailImageMarkup4 {
            get {
                return ResourceManager.GetString("JailImageMarkup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img data-href=&quot;{0}&quot; src=&quot;/Images/blank.gif&quot; width=&quot;{1}&quot; height=&quot;{2}&quot; class=&quot;jail {3} hide&quot; alt=&quot;{4}&quot; /&gt;&lt;noscript&gt;&lt;img property=&quot;sc:image&quot; src=&quot;{0}&quot; width=&quot;{1}&quot; height=&quot;{2}&quot; class=&quot;{3}&quot; alt=&quot;{4}&quot; style=&quot;{5}&quot; /&gt;&lt;/noscript&gt;.
        /// </summary>
        public static string JailImageMarkup5 {
            get {
                return ResourceManager.GetString("JailImageMarkup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to male.
        /// </summary>
        public static string MaleGender {
            get {
                return ResourceManager.GetString("MaleGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;#map1&quot;).gMap({{ markers: [{{ latitude: {0}, longitude: {1}, html: &quot;{2}&quot;, popup: true }}], zoom: {3} }});.
        /// </summary>
        public static string Map1 {
            get {
                return ResourceManager.GetString("Map1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;#map1&quot;).gMap({{ markers: [{{ latitude: {0}, longitude: {1}, popup: false }}], zoom: {2} }});.
        /// </summary>
        public static string Map2 {
            get {
                return ResourceManager.GetString("Map2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical files.
        /// </summary>
        public static string PhysicalFiles {
            get {
                return ResourceManager.GetString("PhysicalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage devices.
        /// </summary>
        public static string StorageDevices {
            get {
                return ResourceManager.GetString("StorageDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual files.
        /// </summary>
        public static string VirtualFiles {
            get {
                return ResourceManager.GetString("VirtualFiles", resourceCulture);
            }
        }
    }
}
