//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraWAF.WebPages.Bll.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeraWAF.WebPages.Bll.Resources.Forums", typeof(Forums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting {0}.
        /// </summary>
        public static string ForumSectionItemErrorMessage {
            get {
                return ResourceManager.GetString("ForumSectionItemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;article&gt;&lt;header&gt;&lt;div class=&quot;statistics&quot;&gt;&lt;section&gt;&lt;span class=&quot;votes&quot;&gt;◊ {9}&lt;/span&gt;&lt;br /&gt;&lt;span class=&quot;favorites&quot;&gt;&lt;i class=&quot;fa fa-star-o&quot;&gt;&lt;/i&gt; {10}&lt;/span&gt;&lt;/section&gt;&lt;/div&gt;&lt;h1&gt;&lt;a href=&quot;{6}&quot;&gt;{8}&lt;/a&gt;&lt;/h1&gt;&lt;/header&gt;&lt;footer&gt;Published &lt;time class=&quot;timeAgo&quot; property=&quot;dc:date dc:created&quot; id=&quot;timePublishedDate&quot; runat=&quot;server&quot; datetime=&quot;{0}&quot; pubdate=&quot;pubdate&quot;&gt;{1}&lt;/time&gt; &amp;bull; Modified &lt;time class=&quot;timeAgo&quot; property=&quot;dc:date dc:modified&quot; id=&quot;timeModifiedDate&quot; runat=&quot;server&quot; datetime=&quot;{2}&quot;&gt;{3}&lt;/time&gt; &amp;bull; Written by &lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForumSectionItemMarkup {
            get {
                return ResourceManager.GetString("ForumSectionItemMarkup", resourceCulture);
            }
        }
    }
}
