//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraWAF.WebPages.Bll.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InitialPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InitialPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeraWAF.WebPages.Bll.Resources.InitialPages", typeof(InitialPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	Vivamus quam ex, suscipit non risus non, cursus malesuada tellus.&lt;/p&gt;.
        /// </summary>
        internal static string FrontPageAsideContent {
            get {
                return ResourceManager.GetString("FrontPageAsideContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;float:left;background: url(&apos;/Images/officebuilding1.jpg&apos;) left 4em no-repeat;width: 50%;height: 55em;background-size: 90%;&quot;&gt;
        ///	&amp;nbsp;&lt;/div&gt;
        ///&lt;div style=&quot;float:right;width: 50%;padding-top: 6.5em;&quot;&gt;
        ///	&lt;h1&gt;
        ///		ExampleCorp is a market leader in example industries&lt;/h1&gt;
        ///	&lt;p&gt;
        ///		Donec lorem nisi, ornare eu erat ac, ullamcorper blandit ex. Nam imperdiet lacus id tellus tempor ultricies.&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string FrontPageHeaderContent {
            get {
                return ResourceManager.GetString("FrontPageHeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section class=&quot;bg0&quot;&gt;
        ///	&lt;div class=&quot;section-contents&quot;&gt;
        ///		&lt;div&gt;
        ///			&lt;h1&gt;
        ///				World class example solutions&lt;/h1&gt;
        ///			&lt;ul class=&quot;center&quot;&gt;
        ///				&lt;li&gt;
        ///					Phasellus pellentesque ornare nisl non dictum. Integer et quam et eros auctor maximus in rhoncus massa.&lt;/li&gt;
        ///				&lt;li&gt;
        ///					Praesent sed est mi. Praesent porttitor magna eu tortor dignissim.&lt;/li&gt;
        ///				&lt;li&gt;
        ///					Aenean accumsan orci sapien, non lobortis ex lobortis eget.&lt;/li&gt;
        ///			&lt;/ul&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/section&gt;
        ///&lt;section class=&quot;bg1&quot;&gt;
        ///	&lt;div class=&quot;sec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FrontPageMainContent {
            get {
                return ResourceManager.GetString("FrontPageMainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front page.
        /// </summary>
        internal static string FrontPageTitle {
            get {
                return ResourceManager.GetString("FrontPageTitle", resourceCulture);
            }
        }
    }
}
