//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraWAF.WebPages.Bll.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeraWAF.WebPages.Bll.Resources.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact form.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;header&gt;&lt;h3&gt;Found &lt;b&gt;1&lt;/b&gt; page:&lt;/h3&gt;&lt;/header&gt;.
        /// </summary>
        public static string Found_1_article {
            get {
                return ResourceManager.GetString("Found_1_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;header&gt;&lt;h3&gt;Found &lt;b&gt;{0}&lt;/b&gt; pages:&lt;/h3&gt;&lt;/header&gt;.
        /// </summary>
        public static string Found_several_articles {
            get {
                return ResourceManager.GetString("Found_several_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string FrontpageMenuItemName {
            get {
                return ResourceManager.GetString("FrontpageMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string LogCritical {
            get {
                return ResourceManager.GetString("LogCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom level({0}).
        /// </summary>
        public static string LogCustom {
            get {
                return ResourceManager.GetString("LogCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational.
        /// </summary>
        public static string LogInformational {
            get {
                return ResourceManager.GetString("LogInformational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string LogVerbose {
            get {
                return ResourceManager.GetString("LogVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LogWarning {
            get {
                return ResourceManager.GetString("LogWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;header&gt;&lt;h3&gt;No pages were found.&lt;/h3&gt;&lt;/header&gt;.
        /// </summary>
        public static string No_articles_where_found {
            get {
                return ResourceManager.GetString("No_articles_where_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait of {0}.
        /// </summary>
        public static string PortraitOf {
            get {
                return ResourceManager.GetString("PortraitOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;article&gt;&lt;header&gt;&lt;div class=&quot;statistics&quot;&gt;&lt;section&gt;&lt;span class=&quot;votes&quot;&gt;◊ {9}&lt;/span&gt;&lt;br /&gt;&lt;span class=&quot;favorites&quot;&gt;&amp;#9734; {10}&lt;/span&gt;&lt;/section&gt;&lt;/div&gt;&lt;h1&gt;&lt;a href=&quot;{6}&quot;&gt;{8}&lt;/a&gt;&lt;/h1&gt;&lt;/header&gt;&lt;footer&gt;Published &lt;time class=&quot;timeAgo&quot; property=&quot;dc:date dc:created&quot; id=&quot;timePublishedDate&quot; runat=&quot;server&quot; datetime=&quot;{0}&quot; pubdate=&quot;pubdate&quot;&gt;{1}&lt;/time&gt; &amp;bull; Modified &lt;time class=&quot;timeAgo&quot; property=&quot;dc:date dc:modified&quot; id=&quot;timeModifiedDate&quot; runat=&quot;server&quot; datetime=&quot;{2}&quot;&gt;{3}&lt;/time&gt; &amp;bull; Written by &lt;a href=&quot;/Account/?id={4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfileDocals {
            get {
                return ResourceManager.GetString("ProfileDocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string RootMenuItemDesc {
            get {
                return ResourceManager.GetString("RootMenuItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-home fa-fw&quot; style=&quot;font-size:1.3em&quot;&gt;&lt;/i&gt;.
        /// </summary>
        public static string RootMenuItemName {
            get {
                return ResourceManager.GetString("RootMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;queryResult&quot;&gt;&lt;article&gt;&lt;header&gt;&lt;hgroup&gt;&lt;h1 class=&quot;clear&quot;&gt;&lt;a href=&quot;{1}&quot;&gt;{0}&lt;/a&gt;&lt;/h1&gt;&lt;h2 class=&quot;clear&quot;&gt;&lt;a href=&quot;{1}&quot;&gt;{1}&lt;/a&gt;&lt;/h2&gt;&lt;/hgroup&gt;&lt;/header&gt;&lt;footer&gt;&lt;div class=&quot;queryResultFooter clear&quot;&gt;Published {2} by &lt;a href=&quot;/Account/?id={4}&quot;&gt;{3}&lt;/a&gt;.&lt;/div&gt;&lt;/footer&gt;&lt;p&gt;{5}&lt;/p&gt;&lt;/article&gt;&lt;/div&gt;.
        /// </summary>
        public static string Search_article_result {
            get {
                return ResourceManager.GetString("Search_article_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;queryResult&quot;&gt;&lt;article&gt;&lt;header&gt;&lt;hgroup&gt;&lt;h1 class=&quot;clear&quot;&gt;&lt;a href=&quot;{1}&quot;&gt;{0}&lt;/a&gt;&lt;/h1&gt;&lt;h2 class=&quot;clear&quot;&gt;&lt;a href=&quot;{1}&quot;&gt;{1}&lt;/a&gt;&lt;/h2&gt;&lt;/hgroup&gt;&lt;/header&gt;&lt;footer&gt;&lt;div class=&quot;queryResultFooter clear&quot;&gt;Published {2} by &lt;a href=&quot;/Account/?id={4}&quot;&gt;{3}&lt;/a&gt;.&lt;/div&gt;&lt;/footer&gt;&lt;div class=&quot;queryResultRollupText clear&quot;&gt;&lt;div class=&quot;queryResultFigure&quot;&gt;&lt;figure&gt;&lt;a href=&quot;{1}&quot;&gt;&lt;img src=&quot;{6}&quot; alt=&quot;{7}&quot; title=&quot;{7}&quot; /&gt;&lt;/a&gt;&lt;/figure&gt;&lt;/div&gt;{5}&lt;/div&gt;&lt;/article&gt;&lt;/div&gt;.
        /// </summary>
        public static string Search_article_result2 {
            get {
                return ResourceManager.GetString("Search_article_result2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;queryResult&quot;&gt;&lt;article&gt;&lt;header&gt;&lt;div class=&quot;queryResultFigure&quot;&gt;&lt;figure&gt;&lt;a href=&quot;{1}&quot;&gt;&lt;img src=&quot;{6}&quot; alt=&quot;{7}&quot; title=&quot;{7}&quot; /&gt;&lt;/a&gt;&lt;/figure&gt;&lt;/div&gt;&lt;hgroup&gt;&lt;h1&gt;&lt;a href=&quot;{1}&quot;&gt;{0}&lt;/a&gt;&lt;/h1&gt;&lt;h2&gt;&lt;a href=&quot;{1}&quot;&gt;{1}&lt;/a&gt;&lt;/h2&gt;&lt;/hgroup&gt;&lt;/header&gt;&lt;footer&gt;&lt;div class=&quot;queryResultFooter&quot;&gt;Published {2} by &lt;a href=&quot;/Account/?id={4}&quot;&gt;{3}&lt;/a&gt;.&lt;/div&gt;&lt;br /&gt;&lt;/footer&gt;&lt;div class=&quot;queryResultRollupText&quot;&gt;{5}&lt;/div&gt;&lt;/article&gt;&lt;/div&gt;.
        /// </summary>
        public static string Search_article_result3 {
            get {
                return ResourceManager.GetString("Search_article_result3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message to {0}.
        /// </summary>
        public static string SendMessageTo {
            get {
                return ResourceManager.GetString("SendMessageTo", resourceCulture);
            }
        }
    }
}
