//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraWAF.WebPages.Cloud {
    
    
    public partial class CloudCommand {
        
        /// <summary>
        /// notifications control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VeraWAF.WebPages.Controls.FormNotification notifications;
    }
}
