//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraWAF.WebPages.Dal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Marketing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Marketing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeraWAF.WebPages.Dal.Resources.Marketing", typeof(Marketing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 to 4 employees.
        /// </summary>
        internal static string CompanySize1 {
            get {
                return ResourceManager.GetString("CompanySize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,000 to 2,499 employees.
        /// </summary>
        internal static string CompanySize10 {
            get {
                return ResourceManager.GetString("CompanySize10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,500 to 4,999 employees.
        /// </summary>
        internal static string CompanySize11 {
            get {
                return ResourceManager.GetString("CompanySize11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,000 to 9,999 employees.
        /// </summary>
        internal static string CompanySize12 {
            get {
                return ResourceManager.GetString("CompanySize12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10,000 employees or more.
        /// </summary>
        internal static string CompanySize13 {
            get {
                return ResourceManager.GetString("CompanySize13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 to 9 employees.
        /// </summary>
        internal static string CompanySize2 {
            get {
                return ResourceManager.GetString("CompanySize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 to 19 employees.
        /// </summary>
        internal static string CompanySize3 {
            get {
                return ResourceManager.GetString("CompanySize3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 to 99 employees.
        /// </summary>
        internal static string CompanySize4 {
            get {
                return ResourceManager.GetString("CompanySize4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 to 499 employees.
        /// </summary>
        internal static string CompanySize5 {
            get {
                return ResourceManager.GetString("CompanySize5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 to 749 employees.
        /// </summary>
        internal static string CompanySize6 {
            get {
                return ResourceManager.GetString("CompanySize6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 750 to 999 employees.
        /// </summary>
        internal static string CompanySize7 {
            get {
                return ResourceManager.GetString("CompanySize7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,000 to 1,499 employees.
        /// </summary>
        internal static string CompanySize8 {
            get {
                return ResourceManager.GetString("CompanySize8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,500 to 1,999 employees.
        /// </summary>
        internal static string CompanySize9 {
            get {
                return ResourceManager.GetString("CompanySize9", resourceCulture);
            }
        }
    }
}
