//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeraWAF.WebPages.Dal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mimetypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mimetypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeraWAF.WebPages.Dal.Resources.Mimetypes", typeof(Mimetypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript file.
        /// </summary>
        internal static string application_javascript {
            get {
                return ResourceManager.GetString("application_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF image file.
        /// </summary>
        internal static string image_gif {
            get {
                return ResourceManager.GetString("image_gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG image file.
        /// </summary>
        internal static string image_jpeg {
            get {
                return ResourceManager.GetString("image_jpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG image file.
        /// </summary>
        internal static string image_png {
            get {
                return ResourceManager.GetString("image_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading Style Sheets file.
        /// </summary>
        internal static string text_css {
            get {
                return ResourceManager.GetString("text_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperText Markup Language file.
        /// </summary>
        internal static string text_html {
            get {
                return ResourceManager.GetString("text_html", resourceCulture);
            }
        }
    }
}
